# Generated by Django 2.1.7 on 2019-12-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0, unique=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Productora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='produce',
            name='productora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Productora'),
        ),
    ]
