# Generated by Django 2.1.7 on 2019-12-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='coste',
            field=models.IntegerField(default=0),
        ),
    ]
