# Generated by Django 2.2.6 on 2019-10-28 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.IntegerField()),
                ('cat2', models.IntegerField()),
                ('cat3', models.IntegerField()),
                ('cat4', models.IntegerField()),
                ('mouse', models.IntegerField()),
                ('cat_turn', models.BooleanField(default=True)),
                ('cat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user_cat', to=settings.AUTH_USER_MODEL)),
                ('mouse_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user_mouse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('target', models.IntegerField()),
                ('date', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_game_game', to='datamodel.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_user_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
