# Generated by Django 2.2.6 on 2019-11-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(default=59),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_user_mouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
