# Generated by Django 2.2.6 on 2019-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_gamestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='ACTIVE',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='CREATED',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='FINISHED',
            field=models.IntegerField(default=2),
        ),
    ]
