# Generated by Django 2.2.6 on 2019-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20191104_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameStatus',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
