# Generated by Django 2.1.7 on 2019-11-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20191111_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-11-17'),
        ),
    ]
