# Generated by Django 2.1.7 on 2019-11-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_auto_20191117_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='val',
            new_name='value',
        ),
    ]
