# Generated by Django 2.2.6 on 2019-12-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0012_auto_20191202_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_being_reproduced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-12-03'),
        ),
    ]
