# Generated by Django 2.2.6 on 2019-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0013_auto_20191203_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='cat_being_moved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='cat_movement',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
