# Generated by Django 2.1.7 on 2019-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0014_auto_20191203_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='cat_being_moved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-12-10'),
        ),
    ]
