# Generated by Django 2.2.6 on 2019-12-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0015_auto_20191210_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-12-11'),
        ),
    ]
