# Generated by Django 2.2.6 on 2019-12-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0016_auto_20191211_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='move_being_reproduced',
            new_name='move_being_reproduced_user1',
        ),
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-12-13'),
        ),
    ]
