# Generated by Django 2.2.6 on 2019-12-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0017_auto_20191213_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_being_reproduced_user2',
            field=models.IntegerField(default=0),
        ),
    ]
